#!/usr/bin/env ruby

# ;)
def pick(arr)
    arr.sample
end

# ;)
BANDS = [
            "Dave Matthews Band",
            "Erykah Badu",
            "Joni Mitchell",
            "Cat Stevens",
            "Guster",
            "Dispatch",
            "early Phil Collins",
            "Ben Folds",
            "Sam Cooke",
            "Carole King"
        ]

# ;)
PLACES = [
            "fern bar",
            "swim-up bar",
            "park",
            "big park",
            "regional music event",
            "free local music event",
            "low-cost local music event",
            "beer tasting event",
            "friend's bbq",
            "lazy river"
         ]

# ;)
EMOTICONS = [ ";)" ]

# ;)
EXPRESSIONS = [
                "bingo",
                "tubular",
                "aw yeah",
                "feels right",
                "emotions just right",
                "everything just right"
              ]

# ;)
BEER_BRANDS = [
                "Sierra Nevada",
                "not hoppy IPA",
                "Corona",
                "Corona",
                "Corona"
              ]

# ;)
GOOD_THINGS = [
                "hanging with a cool ex",
                "playing pool but not for money",
                "avoiding a nail in the road",
                "meeting Sade",
                "almost meeting Sade",
                "inner-tubing down the Nile with a hippo",
                "reading about Mars and just loving science",
                "snorkeling for the first time",
                "talking to Sade about her trip to Costa Rica",
                "discovering $5 in my pocket and giving it away",
                "an unexpected sunset"
              ]

saying = """
Someone just put on %s. %s. That's just what it's like at this %s.
Feels like %s.

%s. %s
""" % [pick(BANDS), pick(BEER_BRANDS), pick(PLACES), pick(GOOD_THINGS), pick(EXPRESSIONS), pick(EMOTICONS)]

puts saying
